### ISSUE TITLE
Error on Building project after importing project

### ISSUE THREAD

**Issue by ghost** [googlesamples/android-ActiveNotifications#11]
when the project is imported and built in androidstudio, the gradle build gives error "error: resource android:attr/colorError not found". Upon inspecting further, colorError attribute was added in API Level 26 and the Application build.gradle file has compile sdk version = 24. This needs to be set to 26 for the application to compile.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
