### ISSUE TITLE
Wrong Link

### ISSUE THREAD

**Issue by kpbird** [googlesamples/android-ActiveNotifications#2]
Readme.md file has following wrong link

_Wrong_
If you've found an error in this sample, please file an issue: https://github.com/googlesamples/android-ActiveNotification

_Correct_
If you've found an error in this sample, please file an issue: https://github.com/googlesamples/android-ActiveNotifications

**Comment by PaulRashidi** [comment]
Will be fixed in the next update.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
