### ISSUE TITLE
Removing summary doesn't update counters

### ISSUE THREAD

**Issue by paul-matthews** [googlesamples/android-ActiveNotifications#4]
Removing the summary notification doesn't update the notification counters.

Steps to reproduce:
- Add one notification // message count 1
- Swipe away notificaiton // message count 0 
- Add 3 notifications // message count 4
- Swipe away summary notification // message count 4

Expected
- Add 3 notifications // message count 4
- Swipe away summary notification // message count 0

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
