### ISSUE TITLE
Removing the notification summary never gets called

### ISSUE THREAD

**Issue by paul-matthews** [googlesamples/android-ActiveNotifications#6]
The sample has code to remove the summary if the number of (non summary) notifications drops to 1. However, this logic is only ever triggered on add, which means it's dead code because if the the summary either wouldn't exist or there would be two or more notifications.

I believe this logic is intended to be triggered on removal of notification.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
